name: fratelli_scuola_app
description: "App per apprendere la lingua italiana"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  #splash screen
  flutter_native_splash: ^2.4.4

# Configuración del splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: lib/presentation/assets/icons/logo.jpg  # imagen principal del splash
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/presentation/assets/icons/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/presentation/assets/icons/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/presentation/assets/icons/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/presentation/assets/icons/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/icons/

 # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

