// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYZS9Bt5b14gJiDoLnfXIo9kUQOcsf8Q',
    appId: '1:332418365050:web:4239dcf678513640572dc3',
    messagingSenderId: '332418365050',
    projectId: 'fratelli-scuola-2bccb',
    authDomain: 'fratelli-scuola-2bccb.firebaseapp.com',
    storageBucket: 'fratelli-scuola-2bccb.firebasestorage.app',
    measurementId: 'G-BCCPZ1C7TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3W0_HORI8BXqUBBu0LEp32iw0IsTR9Q',
    appId: '1:332418365050:android:04971c761d8a2f0a572dc3',
    messagingSenderId: '332418365050',
    projectId: 'fratelli-scuola-2bccb',
    storageBucket: 'fratelli-scuola-2bccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNmGrtsGoxAcnHu4ckONFb2OM9aSUd-w',
    appId: '1:332418365050:ios:2774ed32d7bf1e79572dc3',
    messagingSenderId: '332418365050',
    projectId: 'fratelli-scuola-2bccb',
    storageBucket: 'fratelli-scuola-2bccb.firebasestorage.app',
    iosBundleId: 'com.example.fratelliScuolaApp',
  );
}
